### PR TITLE
Resolves #14 - Passes Feathers params to service hooks

### LINKED ISSUE #14: Feathers params not available to user service hooks
### Steps to reproduce

```
feathers()
    .configure(hooks())
    .configure(rest())
    .configure(socketio((io) => {
        io.use((socket, next) => {
            socket.feathers.data = 'Hello, world';
            next();
        });
    }))
    .use((req, res, next) => {
        req.feathers.data = 'Hello world';
        next();
    });
```

The above should give us feathers parameters for both RESTful and Socket requests, and indeed under any other circumstance it does!

The issue here is specifically with https://github.com/feathersjs/feathers-authentication-local/blob/master/src/verifier.js#L73, wherein we set the query, but do not pass in the feathers params.

### Expected behavior

A `find` hook on the user service should be provided with any Feathers params specified in socket and rest middleware.

### Actual behavior

The `find` hook on the user service does not receive any additional data other than the query constructed at https://github.com/feathersjs/feathers-authentication-local/blob/master/src/verifier.js#L67

### System configuration

**Module versions** (especially the part that's not working):

- `feathers-authentication-local` - 0.3.4

I've fixed the issue locally, but without sufficient quality for a PR. Will clean up and PR shortly!

### PR DESCRIPTION
**Pull request by thomas-p-wilson**
### Summary

Resolves the issue set forth in #14, where Feathers params specified in REST and Socket middleware are not passed through to the user service during authentication.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request. Is this fix working for you? The problem is that user services should discard the password field when `params.provider` is set (see https://github.com/feathersjs/generator-feathers/blob/master/generators/service/templates/hooks-user.js#L29) so there is no way for local authentication to compare password when passing it through. We could make a copy or `params` and `omit(params, 'provider')`

**Comment by thomas-p-wilson** [comment]
Ahh yes, I understand. It _does_ work for me, but that's an excellent
point. I'm on the road at the moment, but once I'm settled I'll update my
PR accordingly.

**Comment by ekryski** [comment]
I want to be **very** careful with this PR. There are potential side-effects (especially security ones) that could occur by passing feathers params to the `users` service during an authentication call.

As per my comment https://github.com/feathersjs/feathers-authentication-local/issues/14#issuecomment-294237514, the lack of params passing was done intentionally so that one can't call authenticate with query params and potentially get another user's id injected into their JWT access token.

**Comment by ekryski** [comment]
@thomas-p-wilson thanks for fixing this up. I'm okay to merge this PR but I still also feel like this is precisely the reason we have custom verifiers, if you need to do something "custom" other than username and password.

Second opinions from others are welcome otherwise I'll just merge this in a bit.

**Comment by thomas-p-wilson** [comment]
If you'd really rather leave it as a custom verified I won't be offended :)

**Comment by marshallswain** [comment]
@thomas-p-wilson could you resolve the small conflict with the latest master?

**Comment by thomas-p-wilson** [comment]
Yep. No problem. Will do in the morning!

**Comment by thomas-p-wilson** [comment]
Pulled down, and merged in master, only to have tests fail. So I pulled
down master on its own, and tests are failing in master.

File: src/verifier.js [hunk 1]
```diff
@@ -71,17 +72,19 @@ class LocalVerifier {
...
+    }, omit(req.params, 'query', 'provider', 'headers', 'session', 'cookies'));
 
     // Look up the entity
-    this.service.find({ query })
+    this.service.find(params)
       .then(response => {
         const results = response.data || response
         if (!results.length) {
-          debug(`a record with ${this.options.usernameField} of '${username}' did not exist`);
+          debug(`a record with ${usernameField} of '${username}' did not exist`);
```
Comment (thomas-p-wilson) [inline src/verifier.js]: Note this additional change. Master did not use the apparently new `username` constant defined on line 72. Figured it was a quick fix :)

**Comment by thomas-p-wilson** [comment]
Rebased my PR. Tests passing. Should be good to go!

**Comment by marshallswain** [comment]
Ha!  This happened to me last night.  It was weird.  The tests passed in Travis.  I pulled them down and they all failed.  Wiped out `node_modules` and reinstalled, but it still failed.  When I wiped out the entire project folder and re-cloned it worked fine.

Thanks.  That was really fast!

**Comment by marshallswain** [comment]
released as `feathers-authentication-local@0.4.2`.  Thank you, @thomas-p-wilson!

**Comment by thomas-p-wilson** [comment]
Cheers!

On Thu, Jun 22, 2017 at 8:43 AM, Marshall Thompson <notifications@github.com

**Comment by ekryski** [comment]
Thanks guys! Nice work!
