### PR TITLE
Return Invalid login message when user doesn’t exist

### LINKED ISSUE #10: Bad error message is returned for invalid credentials
### Steps to reproduce

Attempt to authenticate with a username and password that don't exist.

### Expected behavior
It should return a proper UnAuthorized error with a nice error message as to what the problem is.

### Actual behavior
It returns an error object without an error message.

### System configuration

**Module versions** (especially the part that's not working): feathers-authentication-local@0.3.3

**NodeJS version**: All

**Operating System**: All

**Browser Version**: All

**React Native Version**: All

**Module Loader**: All

### PR DESCRIPTION
**Pull request by marshallswain**
Will fix #10 once the test is fixed.

### CODE REVIEW

File: src/verifier.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ class LocalVerifier {
         const payload = { [`${this.options.entity}Id`]: id };
         done(null, entity, payload);
       })
-      .catch(error => error ? done(error) : done(null, error));
+      .catch(error => error ? done(error) : done(null, error, { message: 'Invalid login' }));
```
Comment (ekryski) [inline src/verifier.js]: Maybe instead of this we should actually just reject with an error instead of returning `false` on line https://github.com/feathersjs/feathers-authentication-local/blob/master/src/verifier.js#L58. What do you think?

I was initially following how passport expects results to come back but I think in reality we do want to reject with either a 404, 400, or 403 error if invalid credentials are passed in. Likely a 404 since it is during the query look up by username that we can't find a user.

Comment (marshallswain) [inline src/verifier.js]: @ekryski Yeah.  I wasn't sure exactly what would happen here: https://github.com/jaredhanson/passport-local/blob/master/lib/strategy.js#L81 where passport does a special check for `!user`, which is probably what you're talking about.  I don't really understand the need to differentiate it.  Why does Passport care?

Comment (ekryski) [inline src/verifier.js]: I think for some passport strategies they respond differently based on the `fail` method being called vs. the `error` method. https://github.com/jaredhanson/passport-local/blob/master/lib/strategy.js#L81

Just trying to track it down to see if there is a difference.

Comment (ekryski) [inline src/verifier.js]: Ya so I think we can go either way here. For local auth it really doesn't matter. The `fail` method is used more with OAuth and OpenID flows because there are more ways that the authentication can actually fail that may not be a result of bad user credentials. https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L129

Comment (ekryski) [inline src/verifier.js]: I think we should stick with your solution @marshallswain. It conforms more to what Passport advocates and also allows the developer to customize things much more. For example, how we handle `fail` calls: https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/authenticate.js#L60-L77

**Comment by sydcanem** [comment]
I'm glad something has been done on this one and I don't have to create my own verifier just to send some useful error. Btw, can I also suggest to add a debug line in https://github.com/feathersjs/feathers-authentication-local/blob/eb47d2b06184cb43c62bf0bc601ce9076cea260a/src/verifier.js#L58 like `debug('Entity not found')`. `Invalid login` is still isn't useful for development purpose.

**Comment by marshallswain** [comment]
@sydcanem very good suggestions.  I'll work that into the PR.

**Comment by sydcanem** [comment]
Thanks @marshallswain.
